version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        platform: linux/arm64
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - .:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        platform: linux/amd64
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"